### ISSUE TITLE
ImageTransformation - dependency issues

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-delivery-sdk-net#284] opened 2021-10-14 12:24 UTC
### Brief bug description
getting these errors
> error CS0433: The type 'ImageUrlBuilder' exists in both 'Kentico.Kontent.ImageTransformation, Version=14.2.1.0, Culture=neutral, PublicKeyToken=null' and 'Kentico.Kontent.Urls, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

### Repro steps

- reference both the latest version of the:
  - Kentico.Kontent.AspNetCore
  - Kentico.Kontent.Delivery
- try to use ImageUrlBuilder or ImageFormat

### Stuff to fix
- re-release https://github.com/Kentico/kontent-aspnetcore with the latest dependency on Kentico.Kontent.Delivery
- https://github.com/Kentico/kontent-delivery-sdk-net/tree/master/Kentico.Kontent.ImageTransformation -> rename the folder to match the project file

**Comment by Simply007** [comment] 2021-10-18 11:43
Steps to fix are OK - thx @petrsvihlik:
* Rename `~/Kentico.Kontent.ImageTransformation` folder to `~/Kentico.Kontent.Urls` and release new minor version
* Upgrade https://github.com/Kentico/kontent-aspnetcore with newly released version `0.12.0` - you can release beta first to test the output
** maybe @petrsvihlik can test the beta out hm? 😉

**Comment by petrsvihlik** [comment] 2021-11-10 15:08
I guess this one is blocked by #292 right?

**Comment by Simply007** [comment] 2021-11-10 15:12
> I guess this one is blocked by #292 right?

We have found a workaround for the releases (#294). But we wanted to walk through all namespaces and fix potential problems and include them into the new major version - #287.

Co currently it is being blocked by #287.

**Comment by petrsvihlik** [comment] 2021-11-10 15:18
right...but I guess that should be pretty easy, right? I think even VS can adjust all namespaces in the whole solution with a single click and then you can just check the git changes to verify. or is there something more tricky?

**Comment by Simply007** [comment] 2021-11-10 15:20
> right...but I guess that should be pretty easy, right? I think even VS can adjust all namespaces in the whole solution with a single click and then you can just check the git changes to verify. or is there something more tricky?

Yeap, it was just not at the top of our backlog. Do you have any estimate, you would like to have it fixed?

**Comment by petrsvihlik** [comment] 2021-11-10 15:22
naah..I was just wondering. I might draft the PR myself if it'd help ya

**Comment by Simply007** [comment] 2021-11-10 15:36
> naah..I was just wondering. I might draft the PR myself if it'd help ya

Thanks. I guess we are fine. We will finish the walkthrough and release another beta (as well as https://github.com/Kentico/kontent-aspnetcore) so that you can test it.

**Comment by Simply007** [comment] 2021-11-12 12:27
I guess @petrsvihlik, you are going to use the new version targeting .NET 6 right?

I have released 16.0.0-beta2 with unified namespaces, but I would release beta 3 targeting .NET 6 as well and then use this beta3 in the newly released version of `Kentico.Kontent.AspNetCore` - `0.12.0-beta1`.

What do you think?

**Comment by petrsvihlik** [comment] 2021-11-12 12:40
agreed and yes, I'm going to target net6. thx

**Comment by Simply007** [comment] 2021-11-12 13:30
Alright - following combination should work for .NET 6 without collision:
* 16.0.0-beta2 - Kentico.Kontent.Delivery
* 0.12.0-beta1 - Kentico.Kontent.AspNetCore

**Comment by petrsvihlik** [comment] 2021-11-12 17:51
Kentico.Kontent.AspNetCore is not published https://www.nuget.org/packages/Kentico.Kontent.AspNetCore/

**Comment by Simply007** [comment] 2021-11-12 17:58
> Kentico.Kontent.AspNetCore is not published https://www.nuget.org/packages/Kentico.Kontent.AspNetCore/

My bad - https://github.com/Kentico/kontent-aspnetcore/actions/runs/1453234533 -> releasing v 0.12.0-beta2

**Comment by petrsvihlik** [comment] 2021-11-12 18:20
this is another blocker and I would strongly advise against it - https://github.com/Kentico/kontent-delivery-sdk-net/pull/300#issuecomment-967316053

**Comment by Simply007** [comment] 2021-11-15 09:53
OK, closing this issue - because the root cause was fixed, and let's continue discussion about a namespace unification in https://github.com/Kentico/kontent-delivery-sdk-net/pull/300#issuecomment-967316053

**Closed by Simply007** 2021-11-15 09:53 UTC
