### ISSUE TITLE
Warning in AssetElementValueConverter

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-delivery-sdk-net#330] opened 2022-05-24 11:00 UTC
### Brief bug description

What went wrong?

`AssetElementValueConverter.GetPropertyValueAsync` is marked as async but does not use await.

### Repro steps

1. Clone the repository
2. Build the solution
see

```plain
C:\projects\kontent-delivery-sdk-net\Kentico.Kontent.Delivery\ContentItems\AssetElementValueConverter.cs(21,35): warning CS1998: This async method lacks 'await' operators and will run 
synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\projects\kontent-delivery-sdk-net\Kentico.Kontent.Delivery\Kentico.Kontent.Delivery.csproj]
C:\projects\kontent-delivery-sdk-net\Kentico.Kontent.Delivery\ContentItems\AssetElementValueConverter.cs(21,35): warning CS1998: This async method lacks 'await' operators and will run 
synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\projects\kontent-delivery-sdk-net\Kentico.Kontent.Delivery\Kentico.Kontent.Delivery.csproj]
```

### Expected behavior

No warning

### Context

Related to #318

**Comment by MiroKentico** [comment] 2022-05-26 13:42
Hi @Simply007,

the problem is, that `GetPropertyValueAsync` uses naming convention for async methods. And in this `AssetElementValueConverter` case, it is really not a problem that it runs synchronously instead. In fact, only converter in our Delivery SDK code that needs to be async is converter for rich text.

For now, in linked PR this issue from warining is fixed by removal of `async` keywoard and creating a new `Task` from the result. This solution is already used in` NodaTimeValueConverterAttribute`.

**Closed** 2022-06-02 11:34 UTC
